<?php

namespace Debril\RssAtomBundle\Driver;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2013-01-26 at 00:11:13.
 */
class HttpPeclDriverTest extends \PHPUnit_Framework_TestCase
{

    const URL = 'https://raw.github.com/alexdebril/rss-atom-bundle/master/Resources/sample-atom.xml';

    /**
     * @var HttpPeclDriver
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new HttpPeclDriver;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {

    }

    /**
     * @covers Debril\RssAtomBundle\Driver\HttpPeclDriver::getResponse
     * @todo   Implement testGetResponse().
     */
    public function testGetResponse()
    {
        if (! class_exists("HttpRequest") )
        {
            $this->markTestIncomplete(
                'This test cannot be run.'
            );

            return;
        }
        $lastModified = new \DateTime;
        $response = $this->object->getResponse(self::URL, $lastModified);

        $this->assertTrue($response instanceof HttpDriverResponse);

        $this->assertInternalType("string", $response->getBody());
        $this->assertGreaterThan(0, strlen($response->getBody()));
    }

}
