<?php

namespace Debril\RssAtomBundle\Provider;
use PHPUnit\Framework\TestCase;
/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2013-01-25 at 23:47:50.
 */
class MockProviderTest extends TestCase
{
    /**
     * @var MockProvider
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new MockProvider();
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers Debril\RssAtomBundle\Provider\MockProvider::getFeedContent
     */
    public function testGetContent()
    {
        $options = array('id' => 1);
        $feed = $this->object->getFeedContent($options);

        $this->assertInstanceOf('FeedIo\FeedInterface', $feed);
    }

    /**
     * @covers Debril\RssAtomBundle\Provider\MockProvider::getFeedContent
     * @expectedException \Debril\RssAtomBundle\Exception\FeedException\FeedNotFoundException
     */
    public function testGet404()
    {
        $options = array('id' => 'not-found');
        $this->object->getFeedContent($options);
    }
}
