<?php

namespace Debril\RssAtomBundle\Protocol\Formatter;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2013-02-10 at 11:42:28.
 */
class FeedAtomFormatterTest extends \PHPUnit_Framework_TestCase
{

    /**
     * @var FeedAtomFormatter
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new FeedAtomFormatter;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {

    }

    /**
     * @covers Debril\RssAtomBundle\Protocol\Formatter\FeedAtomFormatter::getString
     * @todo   Implement testGetString().
     */
    public function testGetString()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Debril\RssAtomBundle\Protocol\Formatter\FeedAtomFormatter::toString
     * @todo   Implement testToString().
     */
    public function testToString()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Debril\RssAtomBundle\Protocol\Formatter\FeedAtomFormatter::toSimpleXml
     * @todo   Implement testToSimpleXml().
     */
    public function testToSimpleXml()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Debril\RssAtomBundle\Protocol\Formatter\FeedAtomFormatter::setMetas
     */
    public function testSetMetas()
    {
        $element = $this->object->getRootElement();

        $content = new \Debril\RssAtomBundle\Protocol\FeedContent();

        $content->setTitle('test title');

        $this->object->setMetas($element, $content);

        var_dump($element);
        //var_dump($element->asXML());
    }

    /**
     * @covers Debril\RssAtomBundle\Protocol\Formatter\FeedAtomFormatter::getRootElement
     * @todo   Implement testGetRootElement().
     */
    public function testGetRootElement()
    {
        $element = $this->object->getRootElement();

        var_dump($element->asXML());
        var_dump($element);
    }

    /**
     * @covers Debril\RssAtomBundle\Protocol\Formatter\FeedAtomFormatter::setFeedContent
     * @todo   Implement testSetFeedContent().
     */
    public function testSetFeedContent()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
