<?php

namespace Debril\RssAtomBundle\Protocol\Formatter;

use Debril\RssAtomBundle\Tests\Protocol\FormatterAbstract;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2013-02-12 at 21:51:18.
 */
class FeedAtomFormatterTest extends FormatterAbstract
{

    /**
     * @var FeedAtomFormatter
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        parent::setUp();
        $this->object = new FeedAtomFormatter();
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {

    }

    /**
     * @covers Debril\RssAtomBundle\Protocol\Formatter\FeedAtomFormatter::toString
     */
    public function testToString()
    {
        $string = $this->object->toString($this->feed);

        $this->assertInternalType('string', $string);
    }

    /**
     * @covers Debril\RssAtomBundle\Protocol\Formatter\FeedAtomFormatter::toDom
     */
    public function testToDom()
    {
        $element = $this->object->toDom($this->feed);

        $this->assertInstanceOf("\DomDocument", $element);
    }

    /**
     * @covers Debril\RssAtomBundle\Protocol\Formatter\FeedAtomFormatter::getRootElement
     */
    public function testGetRootElement()
    {
        $element = $this->object->getRootElement();

        $this->assertInstanceOf("\DomDocument", $element);
        $this->assertEquals('feed', $element->firstChild->nodeName);
    }

    /**
     * @covers Debril\RssAtomBundle\Protocol\Formatter\FeedAtomFormatter::setMetas
     */
    public function testSetMetas()
    {
        $element = $this->object->getRootElement();

        $this->object->setMetas($element, $this->feed);
        $this->assertInstanceOf("\DomDocument", $element);
    }

    /**
     * @covers Debril\RssAtomBundle\Protocol\Formatter\FeedAtomFormatter::setEntries
     * @covers Debril\RssAtomBundle\Protocol\Formatter\FeedAtomFormatter::addEntry
     */
    public function testSetEntries()
    {
        $this->_testSetEntries($this->object);
    }

}
