<?php

namespace Debril\RssBundle\Protocol;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2013-01-27 at 00:18:14.
 */
class FeedReaderTest extends \PHPUnit_Framework_TestCase
{

    /**
     * @var FeedReader
     */
    protected $object;



    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new FeedReader(new \Debril\RssBundle\Driver\FileDriver);

    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {

    }

    /**
     * @covers Debril\RssBundle\Protocol\FeedReader::addParser
     * @todo   Implement testAddParser().
     */
    public function testAddParser()
    {
        $parser = new Parser\AtomParser;
        $this->object->addParser($parser);

        $this->assertAttributeEquals(array($parser), 'parsers', $this->object);
    }

    /**
     * @covers Debril\RssBundle\Protocol\FeedReader::getDriver
     * @todo   Implement testGetDriver().
     */
    public function testGetDriver()
    {
        $this->assertInstanceOf(
                    "\Debril\RssBundle\Driver\HttpDriver",
                    $this->object->getDriver()
                );
    }

    /**
     * @covers Debril\RssBundle\Protocol\FeedReader::getFeedContent
     * @expectedException Debril\RssBundle\Protocol\Parser\ParserException
     */
    public function testGetFeedContentException()
    {
        $url = dirname(__FILE__) . '/../../Resources/sample-rss.xml';

        $this->object->getFeedContent($url, new \DateTime);
    }

    /**
     * @covers Debril\RssBundle\Protocol\FeedReader::getFeedContent
     */
    public function testGetRssFeedContent()
    {
        $url = dirname(__FILE__) . '/../../Resources/sample-rss.xml';

        $this->object->addParser(new Parser\RssParser);
        $feed = $this->object->getFeedContent($url, new \DateTime);

        $this->assertInstanceOf("\Debril\RssBundle\Protocol\FeedContent", $feed);

        $item = $feed->current();
        $this->assertInstanceOf("\Debril\RssBundle\Protocol\Item", $item);

        $this->assertNotNull($item->getId());
        $this->assertNotNull($item->getLink());
        $this->assertNotNull($item->getTitle());
        $this->assertNotNull($item->getSummary());
        $this->assertInstanceOf("\DateTime", $item->getUpdated());
    }

    /**
     * @covers Debril\RssBundle\Protocol\FeedReader::getFeedContent
     */
    public function testGetAtomFeedContent()
    {
        $url = dirname(__FILE__) . '/../../Resources/sample-atom.xml';
        $this->object->addParser(new Parser\AtomParser);

        $feed = $this->object->getFeedContent($url, new \DateTime);

        $this->assertInstanceOf("\Debril\RssBundle\Protocol\FeedContent", $feed);

        $item = $feed->current();
        $this->assertInstanceOf("\Debril\RssBundle\Protocol\Item", $item);

        $this->assertNotNull($item->getId());
        $this->assertNotNull($item->getLink());
        $this->assertNotNull($item->getTitle());
        $this->assertNotNull($item->getSummary());
        $this->assertInstanceOf("\DateTime", $item->getUpdated());
    }


    /**
     * @covers Debril\RssBundle\Protocol\FeedReader::getResponse
     */
    public function testGetResponse()
    {
        $url = dirname(__FILE__) . '/../../Resources/sample-atom.xml';
        $this->object->addParser(new Parser\AtomParser);
        $response = $this->object->getResponse($url, new \DateTime);

        $this->assertInstanceOf("Debril\RssBundle\Driver\HttpDriverResponse", $response);
    }

    /**
     * @covers Debril\RssBundle\Protocol\FeedReader::parseBody
     * @todo   Implement testParseBody().
     */
    public function testParseBody()
    {
        $url = dirname(__FILE__) . '/../../Resources/sample-rss.xml';
        $this->object->addParser(new Parser\RssParser);

        $response = $this->object->getResponse($url, new \DateTime);

        $feed = $this->object->parseBody($response);

        $this->assertInstanceOf("\Debril\RssBundle\Protocol\FeedContent", $feed);
    }

    /**
     * @covers Debril\RssBundle\Protocol\FeedReader::getAccurateParser
     * @todo   Implement testGetAccurateParser().
     */
    public function testGetAccurateParser()
    {
        $this->object->addParser(new Parser\RssParser);
        $this->object->addParser(new Parser\AtomParser);

        $url = dirname(__FILE__) . '/../../Resources/sample-rss.xml';

        $rssBody = $this->object->getResponse($url, new \DateTime)->getBody();

        $this->assertInstanceOf(
                                    "Debril\RssBundle\Protocol\Parser\RssParser",
                                    $this->object->getAccurateParser(new \SimpleXMLElement($rssBody) )
                        );

        $url = dirname(__FILE__) . '/../../Resources/sample-atom.xml';

        $atomBody = $this->object->getResponse($url, new \DateTime)->getBody();

        $this->assertInstanceOf(
                                    "Debril\RssBundle\Protocol\Parser\AtomParser",
                                    $this->object->getAccurateParser(new \SimpleXMLElement($atomBody))
                        );

    }

}
