<?php

namespace Debril\RssAtomBundle\Protocol;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2013-01-27 at 00:26:35.
 */
class ParserTest extends \PHPUnit_Framework_TestCase
{

    /**
     * @covers Debril\RssAtomBundle\Protocol\Parser::convertToDateTime
     * @expectedException Debril\RssAtomBundle\Protocol\Parser\ParserException
     */
    public function testconvertToDateTimeException()
    {
        $string = '09-12-2012';
        Parser::convertToDateTime($string);
    }

    /**
     * @covers Debril\RssAtomBundle\Protocol\Parser::convertToDateTime
     */
    public function testconvertToDateTime()
    {
        $string = '2003-12-13T18:30:02Z';
        $date = Parser::convertToDateTime($string, \DateTime::RFC3339);

        $this->assertInstanceOf('\DateTime', $date);

        $this->assertEquals("13/12/2003", $date->format("d/m/Y"));
    }

}
